#server:
#  port: 8761
#  servlet:
#    context-path: /eureka
#
#spring:
#  application:
#    name: eureka-server
#  cloud:
#    inetutils:
#      preferred-networks:
#        - 192.168
#      ignoredInterfaces:
#        - enp0s3
#        - docker0
#  security:
#    user:
#      name: zimug
#      password: centerpwd
#
#eureka:
#  instance:
#    hostname: peer3
#    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}
#    health-check-url: http://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/actuator/health
#  client:
#    #从其他两个实例同步服务注册信息
#    fetch-registry: true
#    #向其他的两个eureka注册当前eureka实例
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://zimug:centerpwd@peer1:8761/eureka/eureka/,http://zimug:centerpwd@peer2:8761/eureka/eureka/
#
