server:
  port: 8761
  servlet:
    context-path: /eureka


spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: se1
    health-check-url: http://${eureka.instance.hostname}:8761/actuator/health
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/